"functions":
- "name": "MSTP_IN_create_msti"
  "file": "./mstp.c"
  "params":
  - "name": "br"
    "type": "bridge_t*"
  - "name": "mstid"
    "type": "__u16"
  "return_type": "bool"
  "signature": "bool MSTP_IN_create_msti(bridge_t *br, __u16 mstid)"
- "name": "handle_worker_event"
  "file": "./worker.c"
  "params":
  - "name": "ev"
    "type": "struct worker_event*"
  "return_type": "static void"
  "signature": "static void handle_worker_event(struct worker_event *ev)"
- "name": "worker_thread_fn"
  "file": "./worker.c"
  "params":
  - "name": "arg"
    "type": "void*"
  "return_type": "static void *"
  "signature": "static void *worker_thread_fn(void *arg)"